# Generated by Django 5.0.1 on 2024-02-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolies'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default=1, max_length=60),
        ),
    ]
