# Generated by Django 5.0.1 on 2024-02-02 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_portfolio_options_portfolio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='ticker',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ticker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.ticker'),
        ),
    ]
