# Generated by Django 5.0.1 on 2024-02-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_portfolio_ticker_portfolio_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
    ]
