# Generated by Django 5.0.1 on 2024-02-03 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_portfolioitem_delete_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['ticker'], 'verbose_name': 'portfolio item', 'verbose_name_plural': 'portfolio items'},
        ),
        migrations.AddField(
            model_name='ticker',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.currency'),
        ),
    ]
