# Generated by Django 5.0.1 on 2024-02-03 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_portfolioitem_options_ticker_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='currency',
            field=models.ForeignKey(blank=True, default='USD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.currency'),
        ),
    ]
