# Generated by Django 5.0.1 on 2024-02-03 23:49

import django.db.models.deletion
import stocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_ticker_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='industry',
        ),
        migrations.AddField(
            model_name='ticker',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.industry'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='currency',
            field=models.ForeignKey(blank=True, default=stocks.models.Currency, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.currency'),
        ),
    ]
