# Generated by Django 5.0.1 on 2024-02-03 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_remove_portfolioitem_industry_ticker_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.industry'),
        ),
    ]
